const env = {
  API_KEY: "YOUR_API_KEY",
  url:"http://ddragon.leagueoflegends.com/cdn/10.18.1/data/pt_BR/champion.json",
  BASE_URL: "api.riotgames.com",
  REGION_URL: [
    "br1",
    "eun1",
    "euw1",
    "jp1",
    "kr",
    "la1",
    "la2",
    "na1",
    "oc1",
    "tr1",
    "ru",
  ],
  languages: [
    "en_US",
    "cs_CZ",
    "de_DE",
    "el_GR",
    "en_AU",
    "en_GB",
    "en_PH",
    "en_SG",
    "es_AR",
    "es_ES",
    "es_MX",
    "fr_FR",
    "hu_HU",
    "id_ID",
    "it_IT",
    "ja_JP",
    "ko_KR",
    "pl_PL",
    "pt_BR",
    "ro_RO",
    "ru_RU",
    "th_TH",
    "tr_TR",
    "vn_VN",
    "zh_CN",
    "zh_MY",
    "zh_TW",
  ],
  HOST: "localhost",
  PORT: "3000",
};

module.exports = env;
